<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!-- Declaraciones DTD-->
<!DOCTYPE agenda [
		<!ELEMENT agenda (contacto*)>
		<!ELEMENT contacto (nombre, apellidos, direccion, telefono+)>
		<!ATTLIST contacto orden CDATA #REQUIRED>
		<!ELEMENT nombre (#PCDATA)>
		<!ELEMENT apellidos (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT telefono (#PCDATA)>
]>
<agenda>
<contacto orden="3">
<nombre>Rosa</nombre>
<apellidos>Díez</apellidos>
<direccion>Calle del olvido nº23</direccion>
<telefono>912339992</telefono>
</contacto>
<contacto orden="2">
<nombre>Artur</nombre>
<apellidos>Mas</apellidos>
<direccion>Plaza de la independencia nº5</direccion>
<telefono>934331333</telefono>
<telefono>654543432</telefono>
</contacto>
<contacto orden="1">
<nombre>Albert</nombre>
<apellidos>Rivera</apellidos>
<direccion>Casa de Malú</direccion>
<telefono>913345542</telefono>
<telefono>661223664</telefono>
<telefono>667773772</telefono>
</contacto>
</agenda>