<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!-- Declaraciones DTD-->
<!DOCTYPE mensaje [
<!ELEMENT mensaje (de, para+, asunto, cuerpo?, adjunto*)>
<!ELEMENT de (#PCDATA)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT cuerpo (#PCDATA)>
<!ELEMENT adjunto (#PCDATA)>
]>

<mensaje>
	 <de>A21YagoVR@iessanclemente.net</de>
	 <para>brais@iessanclemente.net</para>
	 <para>pedro@edu.xunta.es</para>
	 <cuerpo></cuerpo>
	 <asunto>Env√≠oche os arquivos</asunto>
	 <adjunto>D:\fotos\dePesca.jpg</adjunto>
	 <adjunto>D:\docs\carta.odt</adjunto>
	 <adjunto>D:\fotos\naCea.jpg</adjunto>
</mensaje>
